defaults: &defaults
  web_hostname: example.org
  mailer_from: noreply@example.org
  # For delivery_method, sendmail_settings and smtp_settings see
  # <http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration>.
  delivery_method: sendmail
  sendmail_settings:
    arguments: '-t -i -f'
  smtp_settings:
    address: localhost
    port: 25
    #openssl_verify_mode: none
  schleuderd:
    host: localhost
    port: 4443
    use_tls: true
    tls_fingerprint:
  api_key:

test:
  <<: *defaults
development:
  <<: *defaults
  web_hostname: localhost:3000
production:
  <<: *defaults
